feat: support dotnet 6.0
aws/porting-assistant-dotnet-client pull request #1102
Opened 2022-02-07 22:32 UTC by huawenm

#### Description of change
[//]: # (What are you trying to fix? What did you change)

#### Issue
[//]: # (Having an issue # for the PR is required for tracking purposes. If an existing issue does not exist please create one.)

#### PR reviewer notes
[//]: # (Let us know if there is anything we should focus on.)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-02-07 22:33 UTC, saikiranakula-amzn submitted a review, later dismissed

2022-02-07 22:37 UTC, cslong requested changes

2022-02-07 22:37 UTC, cslong commented on src/PortingAssistant.Client/PortingAssistantCLI.cs
> +        [Option('t', "target", Required = false, Default = "netcoreapp3.1", HelpText = "Target framework: net6.0, net5.0,  netcoreapp3.1 or netstandard2.1, by default is netcoreapp3.1")]
update the default to net6.0

2022-03-10 22:40 UTC, saikiranakula-amzn approved these changes

2022-03-11 01:45 UTC, closed without merging