Add Incremental Analysis
aws/porting-assistant-dotnet-client pull request #83
Opened 2021-04-22 22:12 UTC by kanikaul-amazon

#### Description of change
[//]: # (What are you trying to fix? What did you change)

Adding Incremental File Level Analysis. This includes :-
1.  New File Analysis API.
2.  Caching of NuGet packages to temp folder for faster assessments.

#### Issue
[//]: # (Having an issue # for the PR is required for tracking purposes. If an existing issue does not exist please create one.)

https://github.com/aws/porting-assistant-dotnet-client/issues/82

#### PR reviewer notes
[//]: # (Let us know if there is anything we should focus on.)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-22 23:20 UTC, huawenm submitted a review, later dismissed

2021-04-26 23:57 UTC, huawenm submitted a review, later dismissed

2021-04-27 00:01 UTC, marknfawaz requested changes

2021-04-27 00:01 UTC, marknfawaz commented on src/PortingAssistant.Client.Analysis/PortingAssistant.Client.Analysis.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
Remove newtonsoft.json (already referenced in portcore nuget)

2021-04-27 01:38 UTC, marknfawaz approved these changes

2021-04-27 02:41 UTC, merged